### ISSUE TITLE
添加了 "--gradio_share" 后运行demo报错

### ISSUE THREAD

**Issue by YYLCyylc** [ttengwang/Caption-Anything#12]
直接运行demo可以成功运行，但是想开放联网端口，所以添加了"--gradio_share"
提示以下错误
```
Initializing ChatBot, load_dict={'VisualQuestionAnswering': 'cuda:0'}
Initializing VisualQuestionAnswering to cuda:0
/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 1.0}
  warnings.warn(
/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 0.4}
  warnings.warn(
/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 0.5}
  warnings.warn(
/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/components.py:164: UserWarning: Unknown style parameter: scale
  warnings.warn(f"Unknown style parameter: {key}")
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 238, in main
    return templates.TemplateResponse(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 244, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 238, in main
    return templates.TemplateResponse(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 244, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 238, in main
    return templates.TemplateResponse(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 244, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 238, in main
    return templates.TemplateResponse(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 244, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 238, in main
    return templates.TemplateResponse(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/anaconda3/envs/caption-anything/lib/python3.8/site-packages/gradio/routes.py", line 244, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
Running on local URL:  http://0.0.0.0:6086
Running on public URL: https://0adaffcff18e829f67.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
^CKeyboard interruption in main thread... closing server.
Killing tunnel 0.0.0.0:6086 <> https://0adaffcff18e829f67.gradio.live
```

**Comment by ttengwang** [comment]
谢谢关注, 升级gradio==3.27可解决此问题

**Comment by YYLCyylc** [comment]
成功运行了，谢谢！
